name: Build ebay bundle package2

env:
  M2_REPOSITORY: '/root/.m2/repository/'
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

on:
  push:
    branches:
      - 'ebay-build2'

jobs:
  build-native-lib:
    runs-on: ubuntu-20.04
    container: apache/gluten:vcpkg-centos-7
    steps:
      - uses: actions/checkout@v1
        with:
          repository: wangyum/packages
          ref: main
          token: ${{ secrets.EBAY_TOKEN }}
      - name: Install packages to $M2_REPOSITORY
        run: |
          mkdir -p $M2_REPOSITORY
          rm -rf $M2_REPOSITORY/io && rm -rf $M2_REPOSITORY/org
          mv ../packages/* $M2_REPOSITORY
          cd $M2_REPOSITORY && find . -name "_*.repositories" | xargs rm -rf # Fix Could not find artifact io.ebay.rheos ...
      - name: Upload bundle package
        uses: actions/upload-artifact@v2
        with:
          name: gluten-velox-bundle-package
          path: $M2_REPOSITORY/org/*
          retention-days: 7
          if-no-files-found: error
